# Site settings
title: kingback
header-img: img/home.jpg
email: aoogcoho@hust.edu.cn
description: "活泼开朗，帅气阳光"
host: "127.0.0.1"
baseurl: ""
url: "http://kingback1.github.io/"
github_username:  kingback1
#zhihu_username: wang-hui-82-91

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","tmp","unless"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
